#!/bin/bash

find "$1" -name '*.jar' | \
    while read -r jar; do
        jar tf $jar | \
            while read -r file; do
                echo -e "$file\t$jar"
            done
    done > /tmp/alljars.txt
